# Project: SMMarble
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o smm_database.o smm_object.o
LINKOBJ  = main.o smm_database.o smm_object.o
LIBS     = -L"C:/Users/HOME/Dev-Cpp/MinGW64/lib" -L"C:/Users/HOME/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/HOME/Dev-Cpp/MinGW64/include" -I"C:/Users/HOME/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/HOME/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/HOME/Dev-Cpp/MinGW64/include" -I"C:/Users/HOME/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/HOME/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/HOME/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = SMMarble.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

smm_database.o: smm_database.c
	$(CC) -c smm_database.c -o smm_database.o $(CFLAGS)

smm_object.o: smm_object.c
	$(CC) -c smm_object.c -o smm_object.o $(CFLAGS)
